### ISSUE TITLE
Project Discussion

### ISSUE THREAD

**Issue by imdarsh** [engineering87/dotnet-design-patterns#2]
I am thinking of building a CMS as a side project just to get my hand on the language as I am new to dotnet. Could you guide me on how could I get started on this idea

**Comment by engineering87** [comment]
Welcome to the .NET world! 
It's a good idea to develop a dedicated project to getting start. On this repository I planned to build a project, probably a Web App, as an example for the use of the 23 design patterns. 
First of all, I recommend you to study the principles of object-oriented programming and the main design patterns starting from the examples. 
Have fun!
